### PR TITLE
Add description of how to install the plugin

### PR DESCRIPTION
**Pull request by paulbutcher**
Add a description of what's required to install the plugin for Node n00bs like myself.

### CODE REVIEW

**Comment by moea** [comment]
`lein deps` is the more succinct way to do that - it may make sense to rather put that in the readme

**Comment by paulbutcher** [comment]
Ah! The trick is knowing that you need to run `lein deps` before running `serverless deploy`. I had no idea (but I do now). Perhaps that is what should go in the readme? 😀

Edit: Sorry - I just reread what you said and realised that that *is* what you said. Yes, I agree. I'll change the pull request with that in mind.

**Comment by paulbutcher** [comment]
Done

**Comment by moea** [comment]
Thanks!

**Pull request merged**
